name: CustomArenas
main: me.serafim.plugin.customarena.CustomArena
version: 1.0.0
description: Esse plugin permite criar várias arenas customizadas
author: nickaleatorioo
softdepend: [SimpleClans]
commands:
  arena:
    description: Existe mais informações sobre os comandos